package com.mvalu.bettr_api.application_journey

enum class LeadRejectedReason(val value: String) {
    DEDUPE("DEDUPE_REJECTED"),
    MARKET_LIST("MARKET_LIST_REJECTED"),
    PINCODE("PINCODE_REJECTED"),
    SERVICE_AREA("SERVICE_AREA_REJECTED"),
    AGE("AGE_REJECTED"),
    SERVICE_AREA_AND_AGE("SERVICE_AREA_AND_AGE_REJECTED"),
    CIBIL("CIBIL_REJECTED"),
    CIBIL_FAILED("CIBIL_FAILED"),
    BUREAU("BUREAU_REJECTED"),
    QDE_REJECTED("QDE_REJECTED"),
    LOCATION_REJECTED("LOCATION_REJECTED"),
    ACCOUNT_VERIFICATION_FAILED("ACCOUNT_VERIFICATION_FAILED"),
    RAZORPAY_ENACH_FAILED("RAZORPAY_ENACH_FAILED"),
    PAN_VERIFICATION_FAILED("PAN_VERIFICATION_FAILED"),
    REASON_UNKNOWN("REASON_UNKNOWN"),
    EMAIL_STATEMENT_FETCH_FAILED("EMAIL_STATEMENT_FETCH_FAILED"),
    RISK_POLICY_EXPIRED("RISK_POLICY_EXPIRED")
}