package com.mvalu.bettr_api.account_statements

enum class MerchantCategory(val value: String) {
    OTHERS("OTHERS"),
    REPAIRS("REPAIRS"),
    ELECTRONICS_AND_DIGITAL_SERVICES("ELECTRONICS AND DIGITAL SERVICES"),
    TRAVEL("TRAVEL"),
    HEALTH("HEALTH"),
    TELECOM("TELECOM"),
    ENTERTAINMENT("ENTERTAINMENT"),
    JEWELLERY("JEWELLERY"),
    SHOPPING("SHOPPING"),
    RESTAURANTS("RESTAURANTS"),
    BEVERAGES("BEVERAGES"),
    GROOMING("GROOMING"),
    EDUCATION("EDUCATION"),
    INTEREST("INTEREST"),
    LATE_FEES("LATE_FEES")
}